# Generated by Django 5.0.6 on 2024-07-14 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("TF-IDF", "TF-IDF"), ("AI", "AI")], max_length=6
                    ),
                ),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "myapp_summaries",
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "myapp_text",
            },
        ),
        migrations.CreateModel(
            name="RougeScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rouge1", models.FloatField()),
                ("rouge2", models.FloatField()),
                ("rougeL", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.summary"
                    ),
                ),
            ],
            options={
                "db_table": "myapp_rougescores",
            },
        ),
        migrations.AddField(
            model_name="summary",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.text"
            ),
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summary",
                        to="myapp.summary",
                    ),
                ),
                (
                    "tfidf_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfidf_summary",
                        to="myapp.summary",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.text"
                    ),
                ),
            ],
            options={
                "db_table": "myapp_comparisons",
            },
        ),
    ]
